#!/usr/bin/env bash
# scripts/install-hooks.sh
#
# Installs git hooks for the heirloom-contracts-backend project.
#
# Currently installs:
#   • pre-commit — secret scanning via gitleaks (scripts/pre-commit-secret-scan.sh)
#
# Run this once after cloning the repository:
#   ./scripts/install-hooks.sh
#
# The script is idempotent: running it multiple times is safe.

set -euo pipefail

# ─── Colour helpers ───────────────────────────────────────────────────────────
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# ─── Resolve paths ────────────────────────────────────────────────────────────
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "${REPO_ROOT}" ]]; then
  echo -e "${RED}Error: must be run inside a git repository.${RESET}" >&2
  exit 1
fi

HOOKS_DIR="${REPO_ROOT}/.git/hooks"
SCRIPTS_DIR="${REPO_ROOT}/scripts"

# ─── Ensure the hooks directory exists ────────────────────────────────────────
mkdir -p "${HOOKS_DIR}"

# ─── Helper: install a single hook ────────────────────────────────────────────
install_hook() {
  local hook_name="$1"        # e.g. "pre-commit"
  local source_script="$2"    # absolute path to the source script

  local hook_target="${HOOKS_DIR}/${hook_name}"

  if [[ ! -f "${source_script}" ]]; then
    echo -e "${RED}Error: source script not found: ${source_script}${RESET}" >&2
    exit 1
  fi

  # If a hook already exists and is NOT our script, back it up rather than
  # silently overwriting it (e.g. pre-existing hooks from other tools).
  if [[ -f "${hook_target}" ]]; then
    # Check whether it already points to our script (idempotency check)
    if grep -qF "pre-commit-secret-scan.sh" "${hook_target}" 2>/dev/null; then
      echo -e "${GREEN}✅ ${hook_name} hook is already installed — no changes made.${RESET}"
      return 0
    fi

    local backup="${hook_target}.bak.$(date +%Y%m%d%H%M%S)"
    echo -e "${YELLOW}⚠️  Existing ${hook_name} hook found — backing up to:${RESET}"
    echo -e "   ${CYAN}${backup}${RESET}"
    cp "${hook_target}" "${backup}"
  fi

  # Write a thin wrapper that delegates to the versioned script in scripts/.
  # Using a wrapper (rather than symlinking) means the hook survives the script
  # being moved without leaving a dangling symlink.
  cat > "${hook_target}" <<HOOK_CONTENT
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run scripts/install-hooks.sh to update.
exec "\$(git rev-parse --show-toplevel)/scripts/pre-commit-secret-scan.sh" "\$@"
HOOK_CONTENT

  chmod +x "${hook_target}"
  echo -e "${GREEN}✅ Installed ${hook_name} hook → ${hook_target}${RESET}"
}

# ─── Install hooks ────────────────────────────────────────────────────────────
echo -e "${CYAN}${BOLD}Installing git hooks for heirloom-contracts-backend…${RESET}"
echo ""

install_hook "pre-commit" "${SCRIPTS_DIR}/pre-commit-secret-scan.sh"

# Make the source script itself executable (in case it was checked out without
# the execute bit, which can happen on some systems or after a fresh clone).
chmod +x "${SCRIPTS_DIR}/pre-commit-secret-scan.sh"

echo ""
echo -e "${GREEN}${BOLD}All hooks installed successfully.${RESET}"
echo ""
echo -e "The ${CYAN}pre-commit${RESET} hook will now scan staged files for secrets before"
echo -e "every ${CYAN}git commit${RESET}. If gitleaks is not installed it will warn but"
echo -e "not block the commit — CI will catch secrets before merge."
echo ""
echo -e "For more details see ${CYAN}docs/secret-scanning.md${RESET}."
